insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (1, 'Farand', 'Blanpein', '3392895740', '202 Dawn Place', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (2, 'Arluene', 'Werndly', '1767237317', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (3, 'Rustin', 'Hollingsbee', '7396764721', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (4, 'Sheilah', 'Houndsom', '1105110029', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (5, 'Kerrin', 'Dragge', '4942109584', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (6, 'Durante', 'Robbe', '3281628555', '9312 Truax Circle', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (7, 'Tansy', 'Reijmers', '1448896023', '31 Bartillon Park', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (8, 'Abdel', 'Philpotts', '6204968220', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (9, 'De', 'Murtell', '9126036085', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (10, 'Ferne', 'Shaudfurth', '6531561634', '0568 Myrtle Court', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (11, 'Aldin', 'Prinne', '7012392791', '4 Loftsgordon Parkway', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (12, 'Falito', 'Hurcombe', '5565511212', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (13, 'Geoffrey', 'Haylands', '9516965821', '1021 Nevada Point', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (14, 'Irita', 'Admans', '2876040157', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (15, 'Caresse', 'Janman', '3483231862', '3224 Manitowish Avenue', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (16, 'Page', 'Spurrior', '1826932119', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (17, 'Emmie', 'Menear', '6236580781', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (18, 'Ruperta', 'Penburton', '7775736724', '38426 Vermont Lane', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (19, 'Myrah', 'Quinlan', '8034295740', '0909 Chinook Hill', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (20, 'Frannie', 'Lambert-Ciorwyn', '2307351516', '1338 Warbler Trail', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (21, 'Juli', 'Oldis', '8911829738', '61 Superior Trail', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (22, 'Jock', 'Deacon', '7697999578', '29908 Mcguire Circle', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (23, 'Daffie', 'Kedslie', '4496858276', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (24, 'Patten', 'Duplan', '3005234002', '70 Haas Street', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (25, 'Sheryl', 'Isacsson', '2509597855', '64 Homewood Crossing', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (26, 'Dyan', 'Rymmer', '4777786071', '37791 Merry Street', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (27, 'Erinn', 'Giffon', '5721641992', '14047 Fairfield Point', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (28, 'Val', 'Jeremaes', '5064323132', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (29, 'Dorothea', 'Stovin', '5863338586', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (30, 'Lanie', 'Kendrew', '5236003063', '52837 Manley Crossing', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (31, 'Kamillah', 'Iwanowski', '6514917570', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (32, 'Annis', 'Yeeles', '1732408651', '7 Caliangt Junction', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (33, 'Jeramie', 'Pucknell', '7753397281', '3 Texas Park', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (34, 'Patience', 'Runsey', '9757716174', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (35, 'Tildi', 'Payfoot', '9103692748', '337 Ryan Terrace', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (36, 'Cullin', 'Goroni', '1682151160', '91 Garrison Circle', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (37, 'Hildagarde', 'Mulqueeny', '1451263266', '934 Florence Hill', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (38, 'Ulrike', 'Franssen', '7342279412', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (39, 'Lavena', 'Peckitt', '5812323090', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (40, 'Winona', 'Dugald', '3531013538', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (41, 'Ellynn', 'Deneve', '4275522272', '232 Butterfield Pass', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (42, 'Rikki', 'Zumbusch', '1125902199', '75240 Park Meadow Point', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (43, 'Heida', 'Fugere', '7642732754', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (44, 'Manfred', 'Andreone', '5268959453', '39 Mayer Circle', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (45, 'Frayda', 'Jumeau', '5668998953', '0 Transport Trail', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (46, 'Ward', 'Pollack', '5418476185', '0330 Lindbergh Pass', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (47, 'Roxanne', 'Bernardes', '7098569720', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (48, 'Lilli', 'Gower', '2932988253', '6844 Ridgeview Court', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (49, 'Stanislaus', 'Roubottom', '3572166108', '44 Merrick Plaza', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (50, 'Clarke', 'Dalla', '6939217774', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (51, 'Chrisse', 'McClean', '6712453975', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (52, 'Lynnell', 'O''Concannon', '4391290604', '41785 Hoepker Place', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (53, 'Jacobo', 'Turvie', '7885951745', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (54, 'Georgiana', 'Archbold', '2914177944', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (55, 'Jefferson', 'Goacher', '1737425365', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (56, 'Osbourn', 'Necolds', '4688855791', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (57, 'Wendel', 'Wilmut', '4051900024', '18070 Armistice Way', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (58, 'Elvyn', 'Dolling', '4006992786', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (59, 'Charlotta', 'Sturney', '4556042031', '189 Oneill Lane', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (60, 'Rowan', 'Sawdon', '7795646212', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (61, 'Cahra', 'Bodycombe', '5713264516', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (62, 'Burgess', 'Boud', '5863199960', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (63, 'Boycie', 'Gotter', '5856054253', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (64, 'Kev', 'Lemanu', '3137727614', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (65, 'Chrissy', 'Brindley', '4045665831', '151 Park Meadow Parkway', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (66, 'Tobin', 'Caulket', '6083884016', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (67, 'Hedvig', 'MacCartair', '9598808475', '14118 New Castle Parkway', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (68, 'Gavan', 'Lazer', '9023485479', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (69, 'Edward', 'Sepey', '7781084465', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (70, 'Bride', 'Lodeke', '8349847460', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (71, 'Giles', 'Bisson', '2599126755', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (72, 'Patricia', 'Jilkes', '9933892043', '88 Bay Center', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (73, 'Amye', 'Stothard', '9491515881', '68816 Ridge Oak Point', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (74, 'Bat', 'Hounihan', '6303894101', '625 Little Fleur Junction', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (75, 'Kimberly', 'Warcop', '3485373901', '202 Elka Hill', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (76, 'Lianna', 'Dulen', '2181161282', '74 Valley Edge Court', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (77, 'Jacklin', 'Paybody', '3022362655', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (78, 'Gabey', 'Craik', '5796734464', '275 Service Park', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (79, 'Bethina', 'Tiplady', '1826497999', '9832 Ruskin Alley', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (80, 'Tillie', 'Scawn', '5657383380', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (81, 'Nikki', 'Treeby', '4062068249', '0 Warrior Lane', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (82, 'Jessie', 'Jursch', '2475528669', '9248 Moland Hill', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (83, 'Monte', 'Briscoe', '5244516869', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (84, 'Corilla', 'Gounod', '4983467295', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (85, 'Annice', 'Joron', '6466579673', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (86, 'Carma', 'Shinn', '5585834889', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (87, 'Lowe', 'Close', '8462261100', '4230 Huxley Junction', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (88, 'Binnie', 'Minucci', '8196385436', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (89, 'Scottie', 'Mimmack', '4835716798', '5332 Stuart Park', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (90, 'Sumner', 'Yea', '2647635756', '6443 Calypso Avenue', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (91, 'Cymbre', 'Farington', '8324834018', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (92, 'Cammie', 'Gansbuhler', '4802167086', '50 Basil Point', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (93, 'Michaeline', 'Gosby', '3295300019', '41 Fallview Hill', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (94, 'Hanni', 'Ewington', '5561940681', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (95, 'Britney', 'Cornall', '6091905897', '96 Cambridge Pass', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (96, 'Eziechiele', 'Nardrup', '1295790365', '780 Corscot Pass', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (97, 'Roxanne', 'McHale', '8724322369', '283 Morning Lane', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (98, 'Murielle', 'La Croce', '9882853879', '5747 Vidon Crossing', 0);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (99, 'Stefan', 'Roebottom', '7259052818', null, 1);
insert into COURIER (Courier_ID, First_Name, Last_Name, Phone_Number, Current_Location, Available) values (100, 'Albertine', 'MacIlhagga', '4756328893', null, 1);
