/*Getting the names to be realistic was enough of a pain, so everything else (including price) is random.*/

insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (1, null, 4142.19, 68, 6, 6, 13, 'DEODORANTS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (2, null, 3311.93, 29, 18, 33, 4, 'TOOTHBRUSHES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (3, null, 2023.46, 15, 1, 38, 17, 'BABY FOOD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (4, null, 4692.28, 25, 19, 7, 8, 'DOG & CAT FOOD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (5, null, 1015.77, 49, 14, 20, 3, 'WATER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (6, null, 3073.5, 44, 8, 19, 9, 'DISH SOAP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (7, null, 2264.11, 46, 20, 31, 5, 'DISPOSABLE PLATES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (8, null, 289.36, 12, 15, 36, 19, 'DISPOSABLE CUPS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (9, null, 4706.65, 13, 9, 3, 2, 'JAMS & APPLESAUCE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (10, null, 942.87, 84, 19, 10, 1, 'EGGO FROZEN WAFFLES & PANCAKES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (11, null, 3409.31, 86, 4, 14, 9, 'HERBS & SEASONINGS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (12, null, 2092.9, 44, 20, 27, 1, 'BAGGED SALADS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (13, null, 2734.67, 42, 17, 9, 13, 'BAGGED SALADS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (14, null, 1898.59, 8, 5, 9, 15, 'COSMETICS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (15, null, 3203.58, 10, 14, 27, 20, 'SAUSAGES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (16, null, 4489.12, 59, 10, 23, 15, 'GIFT CARDS (AMAZON');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (18, null, 4930.15, 25, 4, 22, 10, 'DISH SOAP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (19, null, 2271.7, 73, 1, 5, 16, 'DOG & CAT FOOD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (20, null, 3699.36, 78, 5, 6, 1, 'WATER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (21, null, 4089.52, 20, 9, 3, 6, 'TOOTHPASTE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (22, null, 2348.66, 49, 5, 21, 12, 'SHOWER GELS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (23, null, 2238.68, 47, 9, 35, 2, 'TISSUES & PAPER TOWELS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (24, null, 1554.07, 51, 19, 6, 7, 'KETCHUP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (25, null, 900.45, 20, 15, 37, 1, 'CANDIES & OTHER SWEETS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (26, 18, 4838.43, 47, 16, 18, 15, 'TABACCO');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (27, null, 1400.53, 39, 13, 38, 6, 'TUNA FISH & CANNED SALMON');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (28, null, 3882.13, 30, 2, 22, 4, 'BLOCK CHEESE & DELI CHEESE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (30, null, 1251.02, 25, 12, 28, 3, 'HONEY & MAPLE SYRUP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (31, null, 4325.38, 92, 10, 28, 19, 'ICE CREAM');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (32, null, 4565.98, 80, 14, 17, 9, 'CHEWING GUM');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (33, 21, 4041.93, 4, 12, 24, 5, 'BEER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (34, null, 3284.08, 64, 12, 14, 11, 'OTHER VITAMINS & SUPLEMENTS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (35, null, 2655.52, 81, 17, 10, 1, 'LEGUMES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (36, null, 4539.2, 37, 7, 9, 19, 'KETCHUP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (37, null, 1588.42, 78, 13, 37, 12, 'CHOCOLATE BARS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (38, null, 443.29, 27, 16, 30, 17, 'TABASCO');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (39, null, 4641.98, 15, 19, 23, 15, 'BREAKFAST BARS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (40, null, 173.66, 94, 6, 7, 19, 'CHEWING GUM');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (41, null, 3013.53, 26, 17, 39, 10, 'PACKAGED MAC & CHEESE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (42, null, 267.93, 7, 10, 36, 17, 'OTHER VITAMINS & SUPLEMENTS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (43, null, 4251.73, 29, 12, 21, 7, 'DELI ROLLS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (44, null, 139.36, 62, 4, 16, 9, 'FRESH FRUITS (ESP. BANANAS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (45, null, 114.77, 27, 10, 23, 7, 'DORITOS & LAY’S)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (46, null, 4389.31, 52, 11, 6, 6, 'BUTTER (QUARTER)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (47, null, 3216.02, 51, 12, 21, 8, 'BUTTER (QUARTER)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (48, null, 1317.49, 7, 18, 1, 3, 'SPRITE) & SOFT DRINKS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (49, null, 197.9, 89, 1, 20, 17, 'FRESH & FROZEN BEEF');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (50, null, 2009.95, 86, 13, 28, 16, 'GIFT CARDS (AMAZON');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (51, null, 2650.56, 49, 13, 4, 4, 'CANDY BARS (KIT KAT');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (52, null, 1184.55, 1, 4, 8, 19, 'EGGO FROZEN WAFFLES & PANCAKES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (53, null, 461.72, 18, 12, 17, 19, 'DISPOSABLE UTENSILS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (54, null, 878.17, 76, 4, 31, 11, 'BUTTER (QUARTER)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (55, null, 608.39, 96, 9, 1, 1, 'BBQ & MUSTARD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (56, null, 302.41, 48, 1, 10, 16, 'DISH SOAP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (57, null, 114.57, 62, 3, 26, 6, 'CANDIES & OTHER SWEETS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (58, null, 199.47, 63, 14, 12, 4, 'SUGAR & SALT');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (59, null, 3332.25, 51, 15, 39, 10, 'PEPPERONI');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (60, null, 3012.0, 58, 9, 11, 3, 'TOMATO PASTE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (61, null, 430.62, 94, 1, 26, 2, 'LEGUMES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (62, null, 367.28, 80, 14, 8, 13, 'DISPOSABLE SHAVING RAZORS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (63, null, 2244.93, 47, 1, 22, 9, 'VINEGAR');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (64, null, 3363.07, 16, 7, 8, 3, 'BREAD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (66, null, 1792.87, 63, 3, 36, 6, 'BABY DISPOSABLE DIAPERS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (67, null, 3213.25, 19, 17, 23, 16, 'TOMATO PASTE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (68, null, 3675.49, 91, 14, 1, 2, 'APPLES & LEMONS)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (69, null, 1107.76, 58, 14, 3, 17, 'TOOTHBRUSHES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (70, null, 2116.67, 65, 20, 12, 5, 'DOG & CAT FOOD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (71, null, 1623.87, 47, 20, 6, 11, 'SODA (COKE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (72, null, 201.81, 49, 6, 6, 14, 'SPRITE) & SOFT DRINKS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (73, null, 1100.59, 99, 20, 13, 5, 'VITAMIN C');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (74, null, 1203.81, 35, 18, 14, 9, 'ITUNES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (75, null, 2183.21, 88, 16, 31, 7, 'FRESH FRUITS (ESP. BANANAS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (76, null, 1568.24, 34, 9, 27, 8, 'WATER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (77, null, 2860.07, 76, 18, 22, 15, 'BREAD');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (78, null, 3094.23, 12, 20, 18, 5, 'DELI ROLLS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (80, null, 2849.94, 24, 9, 18, 14, 'KETCHUP');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (81, null, 4979.47, 21, 3, 20, 1, 'SUGAR & SALT');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (82, null, 4045.34, 26, 10, 13, 16, 'LEGUMES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (83, null, 1000.31, 7, 13, 17, 2, 'TOMATO PASTE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (84, null, 4544.92, 39, 8, 7, 12, 'FISH)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (85, null, 2718.42, 20, 5, 34, 12, 'WATER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (87, null, 1639.89, 38, 2, 39, 19, 'ICE CREAM');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (88, null, 2339.95, 66, 18, 3, 5, 'ICE CUBES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (89, null, 57.46, 2, 12, 38, 3, 'PEANUT BUTTER');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (90, null, 4798.44, 66, 11, 23, 2, 'TOMATO PASTE');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (91, null, 3704.1, 38, 10, 10, 18, 'CREAM & CREAM DESSERTS (LIKE COOL WHIP)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (92, null, 4252.85, 23, 5, 28, 11, 'BISCUITS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (93, null, 3582.95, 50, 3, 21, 4, 'ZALANDO ETC.)');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (94, null, 1335.59, 23, 17, 28, 2, 'EGGS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (95, null, 4572.47, 32, 9, 12, 18, 'BISCUITS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (96, null, 2685.91, 98, 19, 11, 4, 'HERBS & SEASONINGS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (97, null, 3161.45, 71, 14, 32, 6, 'DETERGENTS & FABRIC SOFTENERS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (98, null, 3883.88, 36, 7, 32, 17, 'BABY DISPOSABLE DIAPERS');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (99, null, 818.49, 54, 8, 27, 20, 'FRUIT JUICES');
insert into ITEM (Item_ID, Age_Requirement, Price, Quantity_Available, Department_Number, Aisle, Shelf_Location, Item_Name) values (100, null, 648.16, 49, 12, 36, 7, 'OLIVE OIL');